//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslandEscape
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Configuration
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Brightness Level")]
        [Required(ErrorMessage = "Select a brightness level.")]
        [Range(0, 100, ErrorMessage = "Brightness level must be between 0 and 100")]
        public int BrightnessLevel { get; set; }

        [Display(Name = "Sound")]
        public bool SoundLevel { get; set; } = true;

        [ForeignKey("User")]
        public string UserId { get; set; }

        public bool Chosen { get; set; }

        public virtual User User { get; set; }
    }
}
