//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslandEscape
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Game
    {

        private string intensityDesc;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.SavdGameStates = new HashSet<SavdGameState>();
        }
    
        /// <summary>
        /// The ID of the game.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// What date and time the game was created.
        /// </summary>
        public System.DateTime Start { get; set; }

        /// <summary>
        /// The difficulty between 1 and 3.
        /// </summary>
        [Display(Name = "Difficulty")]
        [Required(ErrorMessage = "Select a difficulty level.")]
        [Range(1, 3, ErrorMessage = "Difficulty level must be between 1 and 3")]
        public int IntensityLevel { get; set; }
    
        /// <summary>
        /// The difficulty description.
        /// </summary>
        public string IntensityDesc
        {
            get
            {
                if(this.intensityDesc == null)
                {
                    if(IntensityLevel >= 3)
                    {
                        this.intensityDesc = "Hard";
                    }else if(IntensityLevel == 2)
                    {
                        this.intensityDesc = "Medium";
                    }else
                    {
                        this.intensityDesc = "Easy";
                    }
                }

                return this.intensityDesc;
            }
        }

        /// <summary>
        /// The collection of saved game states associated with this game.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavdGameState> SavdGameStates { get; set; }
    }
}
