//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslandEscape
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.SavdGameStates = new HashSet<SavdGameState>();
        }

        private string intensityDesc;
    
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public int IntensityLevel { get; set; }

        public string IntensityDesc
        {
            get
            {
                if(this.intensityDesc == null)
                {
                    if(IntensityLevel >= 3)
                    {
                        this.intensityDesc = "Hard";
                    }
                    else if(IntensityLevel == 2)
                    {
                        this.intensityDesc = "Medium";
                    }
                    else
                    {
                        this.intensityDesc = "Easy";
                    }
                }

                return this.intensityDesc;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavdGameState> SavdGameStates { get; set; }
    }
}
